---
sensor:
  - platform: p2000
    name: Tilburg
    regios: 20,21
    disciplines: 1,2,3,4
    radius: 15000
  - platform: version
    name: Beta
    beta: true
    image: qemux86-64
    source: hassio
  - platform: version
    name: Installed
  - platform: version
    name: Stable
    beta: false
    image: qemux86-64
    source: hassio