---
blueprint:
  name: Volume Control
  description: 'Time based volume control of you media devices'
  domain: automation
  input:
    media:
      name: Media Players
      description: 'Media player to use.'
      default: []
      selector:
        target:
          entity:
            domain: media_player
    time_up:
      name: Up Time
      description: 'The time the volume goes up.'
      default: '00:00:00'
      selector:
        time:
    time_down:
      name: Down Time
      description: 'The time the volume goes down.'
      default: '00:00:00'
      selector:
        time:
    volume_up:
      name: High Volume level
      description: 'The high volume level, level goes the this value on given time '
      default: 0.6
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    volume_down:
      name: Low Volume level
      description: 'The low volume level, level goes the this value on given time '
      default: 0.2
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider

mode: single

trigger:
  - platform: time_pattern
    minutes: /30
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
action:
  - choose:
      - conditions:
          - condition: time
            before: !input 'time_up'
            after: !input 'time_down'
        sequence:
          - service: media_player.volume_set
            target: !input 'media'
            data:
              volume_level: !input 'volume_up'
      - conditions:
          - condition: time
            before: !input 'time_down'
            after: !input 'time_up'
        sequence:
          - service: media_player.volume_set
            target: !input 'media'
            data:
              volume_level: !input 'volume_down'
