---
- id: d65610cc-f200-471f-be17-cc73592f7f32
  alias: Main Bedroom - Cover Close
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        unique_id: '08:6b:d7:ff:fe:5d:b1:49:1:0x0102'
        command: down_close
  action:
    - service: cover.close_cover
      data:
        entity_id: cover.main_bedroom_cover
