---
- id: ea42a96f-c295-410a-9e2b-26dbc20005e7
  alias: Main Bedroom - Cover Open
  mode: single
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        unique_id: '08:6b:d7:ff:fe:5d:b1:49:1:0x0102'
        command: up_open
  action:
    - service: cover.open_cover
      data:
        entity_id: cover.main_bedroom_cover
