---
alias: Set WLED Effect
mode: single
sequence:
  - service: wled.effect
    data:
      effect: '{{ states(''input_select.wled_effect'') }}'
      intensity: '{{ states(''input_number.wled_intensity'') | int }}'
      palette: '{{ states(''input_select.wled_palette'') }}'
      reverse: '{{ states(''input_boolean.wled_reverse'') }}'
      speed: '{{ states(''input_number.wled_speed'') | int }}'
    entity_id:
      - light.wled_elyza
      - light.wled_santi
