---
blueprint:
  name: Person Home Blueprint
  description: |
    trigger an action if somebody comes home.
  domain: automation
  input:
    personone:
      name: Person 1
      default: ""
      description: Person to use
      selector:
        entity:
          domain: person
    persontwo:
      name: Person 2
      default: ""
      description: Person to use
      selector:
        entity:
          domain: person
    service:
      name: Action to run
      description: Action to run after person comes home
      default:
      selector:
        action:
mode: single

trigger:
  - platform: state
    entity_id: !input personone
    from: not_home
    to: home
  - platform: state
    entity_id: !input persontwo
    from: not_home
    to: home
action: !input service
