---
- id: b4e62d03-1fd7-4ca8-9b09-6ab19d737324
  alias: Hallway - Light On When Dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - device_tracker.in2023
        - device_tracker.iphone_van_marietje
      to: home
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: below_horizon
            - condition: or
              conditions:
                - condition: state
                  entity_id: device_tracker.in2023
                  state: home
                - condition: state
                  entity_id: device_tracker.iphone_van_marietje
                  state: home
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.hallway
      default:
        - delay: 00:05:00
        - service: light.turn_off
          data:
            entity_id: light.hallway
