---
- id: 74171a8e-14f2-4d6d-a973-4e896d2ee509
  alias: Patio - Recycle Bin Light
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door_sensor
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.kitchen_door_sensor
              state: 'on'
            - condition: state
              entity_id:
                - light.patio_led_1
                - light.patio_led_2
              state: 'off'
          sequence:
            - service: light.turn_on
              data:
                entity_id:
                  - light.patio_led_1
                  - light.patio_led_2
      default:
        - service: light.turn_off
          data:
            entity_id:
              - light.patio_led_1
              - light.patio_led_2
