---
- id: 949d4f94-5115-4ef3-92bf-53be7b5df221
  alias: Toilet - Light
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
    - platform: state
      entity_id:
        - binary_sensor.toilet_motion
        - switch.toilet_light
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.toilet_motion
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.toilet_light
      default:
        - delay: 00:05:00
        - service: switch.turn_off
          entity_id: switch.toilet_light
