---
- platform: group
  name: Backyard Lights
  entities:
    - light.patio
    - light.barn_light
    - light.small_barn_light
    - light.flood_light
    - light.barn_led
    - light.main_switch_backyard
