---
# make all switches that are lights an actual light
- platform: switch
  name: Closet Light
  entity_id: switch.closet_light
- platform: switch
  name: Toilet Light
  entity_id: switch.toilet_light
- platform: switch
  name: Garden Flood Light
  entity_id: switch.garden_flood_light
- platform: switch
  name: Bedroom Santi
  entity_id: switch.bedroom_santi
- platform: switch
  name: Nightlight Santi
  entity_id: switch.wled_santi_nightlight
- platform: switch
  name: Nightlight Elyza
  entity_id: switch.wled_elyza_nightlight
- platform: switch
  name: Kitchen Spots
  entity_id: switch.kitchen_spots
