---
- id: f60212cf-2bfb-4550-ad59-c2e5bba421a1
  alias: Small Bedroom - Light
  mode: single
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      unique_id: 'd0:cf:5e:ff:fe:ce:9f:b6:1:0x0006'
      command: 'on'
  action:
    - service: light.toggle
      data:
        entity_id: light.small_bedroom_light
