---
- id: 67614465-a5b9-42d1-8442-5df1914fb432
  alias: Livingroom - Sunset
  mode: single
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
    - platform: state
      entity_id: sensor.lux_sensor
  action:
    - choose:
        - conditions:
            - condition: time
              after: '16:00:00'
              before: '21:00:00'
            - condition: state
              entity_id:
                - light.closet_light
                - light.kitchen_spots
                - light.livingroom_spots
              state: 'off'
            - condition: numeric_state
              entity_id: sensor.lux_sensor
              below: 4.0
            - condition: or
              conditions:
                - condition: state
                  entity_id: person.remco
                  state: home
                - condition: state
                  entity_id: person.annemarie
                  state: home
          sequence:
            - service: light.turn_on
              entity_id:
                - light.closet_light
                - light.kitchen_spots
                - light.livingroom_spots
