---
- id: de1b009c-b228-476a-961b-d70b04f411c1
  alias: System - Backups
  trigger:
    platform: time
    at: '04:30'
  action:
    - service: script.turn_on
      entity_id: script.1586605829719
    - delay:
        minutes: 30
    - service: script.turn_on
      entity_id: script.1586605797020