---
- id: 7a8a7141-3cef-4963-903e-c3d26480155d
  alias: System - Beta Week
  trigger:
    platform: state
    entity_id: calendar.home_assistant_devs
    to: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.beta_week