---
- id: d7040655-c75a-4528-a254-f499a73be6a4
  alias: System - Mqtt Reboot
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
  action:
    service: mqtt.publish
    data:
      topic:
        - cmnd/B_Closet/state
        - cmnd/Hallway_Light/state
        - cmnd/kitchen_switch/state
        - cmnd/lsc_rgb/state
        - cmnd/Pow_R2/state
        - cmnd/Light_Switch_Santi/state
        - cmnd/Toilet_Light/state
      payload: ''
