---
- id: system_volume_control
  alias: System - Volume Control
  trigger:
    - platform: time
      at: '8:30'
    - platform: time
      at: '20:00'
  action:
    - choose:
        - conditions:
            - condition: time
              before: '8:30'
              after: '20:00'
          sequence:
            - service: media_player.volume_set
              data:
                entity_id:
                  - media_player.keuken_speaker
                  - media_player.woonkamer_speaker
                  - media_player.sonos
                  - media_player.patio
                  - media_player.google_hub
                volume_level: 0.1
      default:
        - service: media_player.volume_set
          data:
            entity_id:
              - media_player.keuken_speaker
              - media_player.woonkamer_speaker
              - media_player.sonos
              - media_player.patio
              - media_player.google_hub
            volume_level: 0.5
