- id: '1605983110471'
  alias: Backyard - Backyard Lights
  trigger:
  - platform: device
    domain: tasmota
    device_id: aac3d2a9098611eb82f1737572196896
    type: button_long_press
    subtype: button_1
    discovery_id: D8F15BE77D0A_button_1_HOLD
  action:
  - service: light.toggle
    data: {}
    entity_id: light.patio
  - service: switch.toggle
    data: {}
    entity_id: switch.main_switch_backyard
  - type: toggle
    device_id: 4816d04af45c11eaaa422f9ea8c2efc1
    entity_id: light.barn_light
    domain: light
  - type: toggle
    device_id: ac478478f45c11eaa577b3c31430ad0d
    entity_id: light.small_barn_light
    domain: light
  - delay: 00:00:05
  - type: turn_on
    device_id: 1ea97b16f45b11ea960391631ef5836e
    entity_id: switch.flood_light
    domain: switch
  - service: light.toggle
    data: {}
    entity_id: light.garden
  mode: single
- id: '1605983172224'
  alias: Barn - Barn Light Switch
  trigger:
  - platform: device
    domain: tasmota
    device_id: aac511f1098611eba6d95103d9cc7fe8
    type: button_long_press
    subtype: button_1
    discovery_id: 2462AB40FFCB_button_1_HOLD
  action:
  - service: light.toggle
    entity_id:
    - light.small_barn_light
    - light.barn_light
  mode: single
- id: '1605983309460'
  alias: Bedroom Santi - Wled
  trigger:
  - platform: device
    domain: tasmota
    device_id: aac48a64098611ebb34f8f93577c1c8c
    type: button_double_press
    subtype: button_1
    discovery_id: 2CF432C02815_button_1_DOUBLE
  action:
  - service: light.toggle
    data:
      entity_id: light.wled_santi
      brightness: 128
  mode: single
- id: '1605983336893'
  alias: Frontyard - Doorbell Light
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur_ding
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.voordeur_ding
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      sequence:
      - service: light.turn_on
        data:
          entity_id: light.hallway
    default:
    - delay: 00:05:00
    - service: light.turn_off
      entity_id: light.hallway
- id: '1605983816671'
  alias: Multiroom - Home Coming
  trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
    - device_tracker.iphone_van_marietje
    - device_tracker.in2023
    to: home
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id:
        - light.closet_light
        - light.kitchen_spots
        - light.livingroom_spots
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: device_tracker.iphone_van_marietje
          state: home
        - condition: state
          entity_id: device_tracker.in2023
          state: home
      sequence:
      - service: light.turn_on
        entity_id:
        - light.closet_light
        - light.kitchen_spots
        - light.livingroom_spots
  mode: single
- id: '1605983905990'
  alias: Multiroom - Wled Nightlights
  trigger:
  - platform: state
    entity_id:
    - light.wled_elyza
    - light.wled_santi
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.wled_santi
        state: 'on'
      sequence:
      - service: switch.turn_on
        entity_id: switch.wled_santi_nightlight
    - conditions:
      - condition: state
        entity_id: light.wled_elyza
        state: 'on'
      sequence:
      - service: switch.turn_on
        entity_id: switch.wled_elyza_nightlight
  mode: single
- id: '1605983936127'
  alias: Multiroom - Lights Off When Away
  trigger:
  - platform: state
    entity_id:
    - person.remco
    - person.annemarie
    to: not_home
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
  action:
    choose:
    - conditions:
      - condition: state
        entity_id: group.all_lights
        state: 'on'
      - condition: state
        entity_id: person.remco
        state: not_home
      - condition: state
        entity_id: person.annemarie
        state: not_home
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      sequence:
      - service: homeassistant.turn_off
        entity_id: group.all_lights
      - service: notify.mobile_app_in2023
        data:
          title: Lights Turned Off!!
          message: Home Assistant Turned The Lights Off!!
- id: '1605983963164'
  alias: WLED Effect
  trigger:
  - platform: state
    entity_id: input_select.wled_effect
  - platform: state
    entity_id: input_number.wled_intensity
  - platform: state
    entity_id: input_select.wled_palette
  - platform: state
    entity_id: input_number.wled_speed
  - platform: state
    entity_id: input_boolean.wled_reverse
  action:
  - service: script.turn_on
    data:
      entity_id: script.wled_effect
  mode: single
- id: '1605984035171'
  alias: Misc - Alarm Clock
  trigger:
  - platform: state
    entity_id: binary_sensor.next_alarm
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: person.remco
    state: home
  action:
  - service: scene.turn_on
    entity_id: scene.morning_lights
  mode: single
- id: '1605984068016'
  alias: Misc - Guest Mode
  trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
    - device_tracker.samsung_carla
    - device_tracker.iphonevwendolyn
    - device_tracker.samsung_louis
  action:
  - choose:
    - conditions:
        condition: state
        entity_id: device_tracker.samsung_carla
        state: home
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
    - conditions:
        condition: state
        entity_id: device_tracker.iphonevwendolyn
        state: home
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
    - conditions:
        condition: state
        entity_id: device_tracker.samsung_louis
        state: home
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode
    default:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode
  mode: single
- id: '1605984089065'
  alias: Misc - Recorder Purged Database
  trigger:
  - platform: time_pattern
    minutes: 12
  action:
  - service: recorder.purge
  mode: single
- id: '1605984106973'
  alias: Misc - Database Repack
  trigger:
  - platform: time
    at: 05:55
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: recorder.purge
    data:
      repack: true
  - service: notify.mobile_app_in2023
    data:
      message: Database Repacked!
  mode: single
- id: '1605984175952'
  alias: Notify - Hacs Repo Added
  trigger:
  - platform: state
    entity_id: sensor.hacs
  condition:
  - condition: template
    value_template: '{{ states(trigger.entity_id) != ''unknown''}}'
  - condition: template
    value_template: '{{ (states(trigger.entity_id) | float) != 0}}'
  action:
  - service: persistent_notification.create
    data_template:
      title: Updates pending in HACS
      message: "{% for repo in state_attr(trigger.entity_id, 'repositories') %}\n\
        \  **{{ repo.display_name }}** _{{ repo[\"installed_version\"] }}_ -> _{{\
        \ repo[\"available_version\"] }}_\n{% endfor %}"
- id: '1605984262914'
  alias: Notify - Home Assistant Started
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.mobile_app_in2023
    data:
      message: Home Assistant Is Starting Up!
  mode: single
- id: '1605984282844'
  alias: Notify - Automations Reloaded
  trigger:
  - platform: event
    event_type: automation_reloaded
  action:
  - service: persistent_notification.create
    data:
      message: Home Asssitant Reloaded All Automations
  mode: single
- id: '1605984300810'
  alias: Notify - Home Asistant Shutdown
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: notify.mobile_app_in2023
    data:
      message: Home Assistant Is Shutting Down... Bye!
  mode: single
- id: '1607284139941'
  alias: Hallway - Light
  description: ''
  trigger:
  - platform: state
    entity_id: person.annemarie
    from: not_home
    to: home
  - platform: state
    entity_id: person.remco
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - type: turn_on
    device_id: aac63ad9098611eba8402b3b5a07ae74
    entity_id: light.hallway
    domain: light
    brightness_pct: 100
  - delay: 00:05:00
  - type: turn_off
    device_id: aac63ad9098611eba8402b3b5a07ae74
    entity_id: light.hallway
    domain: light
  mode: restart
- id: '1607786236228'
  alias: Toilet - Motion Light
  description: ''
  use_blueprint:
    path: home-assistant/motion_light.yaml
    input:
      no_motion_wait: '300'
      motion_entity: binary_sensor.toilet_motion
      light_target:
        entity_id: light.toilet_light
- id: '1607786298747'
  alias: Basement - Motion Light
  description: ''
  use_blueprint:
    path: home-assistant/motion_light.yaml
    input:
      no_motion_wait: '60'
      motion_entity: binary_sensor.basement_motion
      light_target:
        device_id: aac5d270098611eb937857059cfc255f
- id: '1607786388042'
  alias: Light Switch Upstairs
  description: ''
  use_blueprint:
    path: r3mcos3/ikea_on_off_remote.yaml
    input:
      remote: 5cc0cafff45a11ea9402ed23ce64464b
      on_button:
      - type: toggle
        device_id: 6c71479d9a39477bb41f3d0e181aeb93
        entity_id: light.small_bedroom_light
        domain: light
      on_button_long:
      - type: toggle
        device_id: c6c692f2e8c65a76f4799b6d4dc8146a
        entity_id: light.wled_elyza
        domain: light
      off_button:
      - type: toggle
        device_id: e3c6227706f54d5c8bf49dbf0ecd49d7
        entity_id: light.main_bedroom_light
        domain: light
      off_button_long:
      - service: light.toggle
        data: {}
        entity_id: light.attic
- id: '1607786514646'
  alias: Light Switch Downstairs
  description: ''
  use_blueprint:
    path: r3mcos3/ikea_on_off_remote.yaml
    input:
      remote: de8debf5faa911eaae7f1bb353807f3d
      on_button:
      - service: light.toggle
        data: {}
        entity_id: light.livingroom_spots
      off_button:
      - type: toggle
        device_id: 5e1a4fc2842e401c8a66a96272680fed
        entity_id: switch.closet_light
        domain: switch
      off_button_long:
      - service: light.toggle
        data: {}
        entity_id: light.livingroom_spots_2
      on_button_long:
      - service: light.toggle
        data: {}
        entity_id: light.livingroom_spots_1
- id: '1607862736401'
  alias: System - Motion Light Watchdog
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: aac5d270098611eb937857059cfc255f
    entity_id: light.basement_closet
    domain: light
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: device
    type: turned_on
    device_id: aac4f98e098611eb9e873b2d79814200
    entity_id: switch.toilet_light
    domain: switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: aac5d270098611eb937857059cfc255f
        entity_id: light.basement_closet
        domain: light
        for:
          hours: 0
          minutes: 2
          seconds: 0
      sequence:
      - type: turn_off
        device_id: aac5d270098611eb937857059cfc255f
        entity_id: light.basement_closet
        domain: light
    - conditions:
      - condition: device
        type: is_on
        device_id: aac4f98e098611eb9e873b2d79814200
        entity_id: switch.toilet_light
        domain: switch
        for:
          hours: 0
          minutes: 5
          seconds: 0
      sequence:
      - type: turn_off
        device_id: aac4f98e098611eb9e873b2d79814200
        entity_id: switch.toilet_light
        domain: switch
    default: []
  mode: single
- id: '1608222290186'
  alias: 'Landing - Cover Remote '
  description: ''
  use_blueprint:
    path: r3mcos3/ikea_open_close_remote.yaml
    input:
      remote: 32671a79f45a11ea9ecd57af3000c80f
      cover: cover.main_bedroom_cover
- id: '1608314282933'
  alias: Livingroom - Sunset Lights
  description: ''
  use_blueprint:
    path: r3mcos3/lux_light.yaml
    input:
      lux_level: '5'
      lux_sensor: sensor.lux_sensor
      lights:
        entity_id:
        - light.livingroom_spots
        - light.closet_light
        - light.kitchen_spots
        - light.christmas_tree
        - light.window_leds
      time: '16:00:00'
      time_before: '20:30:00'
      time_after: '12:00:00'
- id: '1608362266535'
  alias: System - Volume Control
  description: ''
  use_blueprint:
    path: r3mcos3/volume_control.yaml
    input:
      volume_down: '0.2'
      media:
        entity_id:
        - media_player.google_hub
        - media_player.kitchen_speaker
        - media_player.livingroom_speaker
        - media_player.sonos_livingroom
        - media_player.sonos_patio
      time_up: 08:30:00
      time_down: '20:30:00'
      volume_up: '0.5'
- id: '1608373619487'
  alias: System - Download Completed
  description: ''
  trigger:
  - platform: event
    event_type: transmission_downloaded_torrent
  action:
  - service: notify.mobile_app_in2023
    data:
      title: Torrent completed!
      message: '{{trigger.event.data.name}}'
  mode: single
- id: '1608488532525'
  alias: Patio - Recycle Bin
  description: ''
  use_blueprint:
    path: reinder83/motion-detect-lights-with-elevation-check.yaml
    input:
      below_elevation: '3'
      motion_entity: binary_sensor.kitchen_door_sensor
      light_target:
        entity_id:
        - light.patio_led_1
        - light.patio_led_2
      no_motion_wait: '120'
- id: '1608628236783'
  alias: Bathroom - Washing Machine Done
  description: ''
  use_blueprint:
    path: Sbyx/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
    input:
      finishing_hysteresis: '5'
      power_sensor: sensor.pow_r2_energy_power
      actions:
      - service: tts.cloud_say
        entity_id: media_player.huiskamer
        data:
          entity_id: media_player.cc.livingroom
          message: wasmachine is klaar!
          options:
            gender: female
          language: nl-NL
      finishing_threshold: '5'
- id: '1608720176984'
  alias: Heating Control
  description: ''
  use_blueprint:
    path: r3mcos3/heating.yaml
    input:
      set_temp: '25'
      heating: climate.woonkamer
      temp_sensor: sensor.livingroom_temp
      person1: person.remco
      person2: person.annemarie
      min_temp: 20
- id: '1608791839747'
  alias: Tag - Hallway
  description: ''
  trigger:
  - platform: tag
    tag_id: 9fcab2aa-c947-40dc-a1a1-b25958049091
  condition: []
  action:
  - service: light.toggle
    data:
      brightness: 255
      color_temp: 225
      white_value: 255
    entity_id: light.hallway
  mode: single
- id: '1608804805725'
  alias: System - Alarm Sound
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.alarm_sound
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.alarm_sound
        state: 'on'
      sequence:
      - service: media_player.play_media
        data:
          media_content_id: /local/alarm1.mp3
          media_content_type: music
        entity_id:
        - media_player.livingroom_speaker
        - media_player.kitchen_speaker
        - media_player.google_hub
    default:
    - service: media_player.media_stop
      data: {}
      entity_id:
      - media_player.livingroom_speaker
      - media_player.kitchen_speaker
      - media_player.google_hub
  mode: single
- id: '1608871383468'
  alias: Livingroom - Heating Override
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.climate_override
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.climate_override
        state: 'on'
      sequence:
      - service: automation.turn_off
        data:
          entity_id: automation.heating_control
      - service: climate.set_temperature
        data:
          entity_id: climate.woonkamer
          temperature: 25
          hvac_mode: heat
    - conditions:
      - condition: numeric_state
        entity_id: sensor.livingroom_temp
        above: '20'
      sequence:
      - service: climate.turn_off
        data:
          entity_id: climate.woonkamer
    default:
    - service: automation.turn_on
      data:
        entity_id: automation.heating_control
  mode: single
- id: '1609067405539'
  alias: System - Low Battery's
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      day: '0'
      exclude:
        entity_id:
        - sensor.iphone_van_marietje_battery_level
        - sensor.in2023_battery_level
      actions:
      - service: notify.mobile_app_in2023
        data:
          title: Low Battery's
          message: 'Low battery warning for: {{sensors}}'
