device_tracker.in2023:
  entity_picture: /local/remco.jpg
device_tracker.iphone_van_marietje:
  entity_picture: /local/anne.jpg
sensor.beta:
  icon: mdi:home-assistant
sensor.installed:
  icon: mdi:home-assistant
sensor.stable:
  icon: mdi:home-assistant
