switch.kast_lamp:
  icon: mdi:lightbulb
switch.pow_r2:
  friendly_name: Pow R2
  icon: mdi:power-socket-eu
switch.sonoff_basic:
  friendly_name: Toilet Light
  icon: mdi:lightbulb
sensor.battery_beneden_multi:
  device_class: battery
sensor.battery_boven_multi:
  device_class: battery
sensor.battery_motion_sensor:
  device_class: battery
device_tracker.life360_remco_verhagen:
  entity_picture: https://life360-img.s3.amazonaws.com/img/user_images/da488a0e-e774-4ce6-9934-30e737d9370f/cb669336-3631-45d1-a2ba-97c15e17f810.jpg?fd=2
  friendly_name: Remco
device_tracker.life360_annemarie:
  friendly_name: Annemarie
sensor.oneplus_charging:
  device_class: power
sensor.wifi_oneplus:
  device_class: signal_strength
sensor.battery_level_oneplus:
  device_class: battery
sensor.oneplus_6_alarm_sensor:
  friendly_name: Oneplus6 Alarm
sensor.battery_level_iphone:
  device_class: battery
sensor.iphone_charging:
  device_class: power
sensor.wifi_iphone:
  device_class: signal_strength
sensor.battery_deur_achter:
  device_class: battery
sensor.battery_deur_voor:
  device_class: battery
sensor.trash_kerstbomen:
  hidden: true
binary_sensor.deur_achter:
  device_class: door
binary_sensor.deur_voor:
  device_class: door
sensor.sonoff_basic_wifi_signal:
  device_class: signal_strength
sensor.trash_firstwastetype:
  friendly_name: Trash Type
  icon: mdi:recycle
sensor.trash_firstdate:
  friendly_name: Trash Date
  icon: mdi:delete-restore
sensor.hassos_version:
  icon: mdi:server-security
sensor.glances_cpu_used:
  friendly_name: CPU Used
  icon: mdi:chip
sensor.glances_disk_used_percent:
  friendly_name: Disk Used
sensor.glances_ram_used_percent:
  friendly_name: RAM Used
sensor.installed_version:
  icon: mdi:home-assistant
sensor.beta_version:
  icon: mdi:test-tube
sensor.supervisor_version:
  icon: mdi:account-supervisor-circle
sensor.stable_version:
  icon: mdi:home-alert
sensor.lenovo_cpu_usage:
  friendly_name: CPU Usage
  icon: mdi:chip
sensor.lenovo_hdd_total_free_space_c:
  friendly_name: HDD Total Free Space (C)
sensor.lenovo_hdd_used_space_c:
  friendly_name: HDD Used Space (C)
binary_sensor.lenovo_connected:
  friendly_name: Connected
sensor.lenovo_ram_usage:
  friendly_name: RAM Usage
binary_sensor.lenovo_charging:
  friendly_name: Charging
sensor.lenovo_remaining_battery:
  friendly_name: Remaining Battery
sensor.potential_breaking_changes:
  friendly_name: Potential Breaking Changes
sensor.lenovo_hdd_total_free_space_d:
  friendly_name: HDD Total Free Space (D)
sensor.lenovo_hdd_used_space_d:
  friendly_name: HDD Used Space (D)
sensor.lenovo_hdd_usage_c:
  friendly_name: HDD Usage (C)
sensor.lenovo_hdd_usage_d:
  friendly_name: HDD Usage (D)
sensor.hacs:
  friendly_name: HACS
person.annemarie:
  entity_picture: /local/anne.jpg
person.remco:
  entity_picture: /local/remco.jpg
sensor.air_quality_pm10:
  icon: mdi:cloud-outline
sensor.air_quality_pm2_5:
  icon: mdi:cloud
binary_sensor.door_sensor_grote_slaapkamer:
  device_class: window
binary_sensor.door_sensor_slaapkamer_santi:
  device_class: window
binary_sensor.door_sensor_bathroom:
  device_class: window
binary_sensor.door_sensor_slaapkamer_elyza:
  device_class: window
group.all_lights:
  hidden: false
binary_sensor.frontdoor:
  device_class: door
binary_sensor.backdoor:
  device_class: door
binary_sensor.bathroom_window:
  device_class: window
binary_sensor.main_bedroom_window:
  device_class: window
binary_sensor.bedroom_santi_window:
  device_class: window
binary_sensor.bedroom_elyza_window:
  device_class: window
binary_sensor.oneplus6:
  device_class: presence
light.nightlight_elyza:
  icon: mdi:led-strip-variant
light.nightlight_santi:
  icon: mdi:led-strip-variant
sensor.temp_bathroom:
  device_class: temperature
sensor.temp_elyza:
  device_class: temperature
sensor.temp_santi:
  device_class: temperature
sensor.updates_available_log:
  unit_of_measurement: Update(s) Available
sensor.mariadb_size:
  icon: mdi:database
binary_sensor.frontdoor_doorwindow:
  device_class: door
binary_sensor.bathroom_doorwindow:
  device_class: window
binary_sensor.elyza_doorwindow:
  device_class: window
binary_sensor.main_bedroom_doorwindow:
  device_class: window
binary_sensor.santi:
  device_class: window
cover.main_bedroom:
  device_class: blind
binary_sensor.santi_window:
  device_class: window
sensor.energy_consumption_tarif_1:
  friendly_name: Energy Consumption (Normal Tarif)
sensor.energy_consumption_tarif_2:
  friendly_name: Energy Consumption (Dal Tarif)
switch.pihole:
  icon: mdi:dns
switch.unifi:
  icon: mdi:wall
switch.glances:
  icon: mdi:eye-outline
switch.pi_hole:
  icon: mdi:pi-hole
switch.watchtower:
  icon: mdi:lighthouse-on
switch.portainer:
  icon: mdi:docker
switch.mqtt:
  icon: mdi:dots-horizontal
switch.home_assistant:
  icon: mdi:home-assistant
switch.home_assistant_dev:
  icon: mdi:home-assistant
