- id: '1599939736078'
  name: Morning Lights
  entities:
    switch.closet_light:
      friendly_name: Closet Light
      state: 'on'
    switch.kitchen_switch:
      friendly_name: Kitchen Spots
      state: 'on'
- id: '1601915244445'
  name: Backyard Scene
  entities:
    light.barn_light:
      min_mireds: 250
      max_mireds: 454
      brightness: 254
      color_temp: 370
      off_brightness:
      friendly_name: Barn Light
      supported_features: 43
      state: 'on'
    light.small_barn_light:
      brightness: 254
      off_brightness:
      friendly_name: Small Barn Light
      supported_features: 41
      state: 'on'
    switch.flood_light:
      friendly_name: Flood Light
      state: 'on'
    switch.main_switch_backyard:
      friendly_name: Main Switch Backyard
      state: 'on'
    light.garden:
      brightness: 0
      entity_id:
      - light.garden_light_1
      - light.garden_light_2
      - light.garden_light_3
      - light.garden_light_4
      friendly_name: Garden
      supported_features: 41
      state: 'on'
    light.patio:
      brightness: 254
      entity_id:
      - light.patio_led_1
      - light.patio_led_2
      - light.patio_led_3
      - light.patio_led_4
      - light.patio_led_5
      - light.patio_led_6
      friendly_name: Patio
      supported_features: 41
      state: 'on'
  icon: mdi:flower-outline
- id: '1607168895164'
  name: Alarm - Lights On
  entities:
    light.hallway:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      brightness: 255
      hs_color:
      - 0
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      effect: '0'
      friendly_name: Hallway
      supported_features: 151
      state: 'on'
    light.kitchen_light:
      brightness: 254
      off_brightness:
      friendly_name: Kitchen Light
      supported_features: 41
      state: 'on'
- id: '1607168929995'
  name: Alarm - Lights Off
  entities:
    light.kitchen_light:
      off_brightness:
      friendly_name: Kitchen Light
      supported_features: 41
      state: 'off'
    light.hallway:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      friendly_name: Hallway
      supported_features: 151
      state: 'off'
- id: '1607177853180'
  name: Alarm Night On
  entities:
    light.main_bedroom_light:
      brightness: 254
      hs_color:
      - 360
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      off_brightness:
      friendly_name: Main Bedroom Light
      supported_features: 57
      state: 'on'
- id: '1607177884472'
  name: Alarm Night Off
  entities:
    light.main_bedroom_light:
      off_brightness:
      friendly_name: Main Bedroom Light
      supported_features: 57
      state: 'off'
