'1607170822154':
  alias: Spot Brightness
  mode: single
  sequence:
  - service: light.toggle
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: '500'
  - service: light.toggle
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: '500'
  - service: light.toggle
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: '500'
  - service: light.toggle
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: '500'
  - service: light.toggle
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: '500'
  - service: light.toggle
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: '500'
