spots_brightness:
  alias: Spots Brightness
  sequence:
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  - delay:
      milliseconds: 500
  - service: light.toggle
    data: {}
    entity_id: light.livingroom_spots
  mode: single
  icon: mdi:spotlight
