'1586605797020':
  alias: Backup Snapshots
  sequence:
  - data: {}
    service: shell_command.ha_backup
'1586605829719':
  alias: Backup HA Config
  sequence:
  - data: {}
    service: shell_command.ha_config_backup
