---
- platform: rest
  resource: !secret pihole_url
  name: Pi-Hole
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret glances_url
  name: Glances
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret unifi_url
  name: Unifi
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret ha_dev_url
  name: Home Assistant Dev
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret ha_url
  name: Home Assistant
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret mqtt_url
  name: Mqtt
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret ha_dockermon
  name: HA Dockermon
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret portainer_url
  name: Portainer
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: !secret watchtower_url
  name: Watchtower
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
