---
- id: 526af30f-a5dd-462f-98f3-3119fab1d70b
  alias: Misc - Guest Mode
  mode: single
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: automation_reloaded
    - platform: state
      entity_id:
        - device_tracker.samsung_carla
        - device_tracker.iphonevwendolyn
        - device_tracker.samsung_louis
  action:
    - choose:
        - conditions:
            condition: state
            entity_id: device_tracker.samsung_carla
            state: home
          sequence:
            - service: input_boolean.turn_on
              entity_id: input_boolean.guest_mode
        - conditions:
            condition: state
            entity_id: device_tracker.iphonevwendolyn
            state: home
          sequence:
            - service: input_boolean.turn_on
              entity_id: input_boolean.guest_mode
        - conditions:
            condition: state
            entity_id: device_tracker.samsung_louis
            state: home
          sequence:
            - service: input_boolean.turn_on
              entity_id: input_boolean.guest_mode
      default:
        - service: input_boolean.turn_off
          entity_id: input_boolean.guest_mode
