---
- id: 7e7b6daa-8670-4da9-b335-98bf68aae7c2
  alias: Misc - Recorder Purged Database
  mode: single
  trigger:
    - platform: time_pattern
      minutes: 12
  action:
    - service: recorder.purge
    - service: notify.mobile_app_in2023
      data:
        message: Database Purged!

- id: 08569ccf-f4e9-4e83-a735-852e66ac7a2a
  alias: Misc - Database Repack
  mode: single
  trigger:
    - platform: time
      at: '05:55'
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: recorder.purge
      data:
        repack: true
    - service: notify.mobile_app_in2023
      data:
        message: Database Repacked!
