---
- id: 15993515-9764-4c08-a22e-161f8a52a5e4
  alias: Misc - Volume Control
  mode: single
  trigger:
    platform: time
    at:
      - '08:30:00'
      - '20:00:00'
  action:
    - choose:
        - conditions:
            - condition: time
              before: input_datetime.volume_down
              after: input_datetime.volume_up
          sequence:
            - service: media_player.volume_set
              data:
                volume_level: 0.5
                entity_id:
                  - media_player.google_hub
                  - media_player.keuken_speaker
                  - media_player.woonkamer_speaker
                  - media_player.huiskamer
                  - media_player.serre
        - conditions:
            - condition: time
              before: input_datetime.volume_up
              after: input_datetime.volume_down
          sequence:
            - service: media_player.volume_set
              data:
                volume_level: 0.2
                entity_id:
                  - media_player.google_hub
                  - media_player.keuken_speaker
                  - media_player.woonkamer_speaker
                  - media_player.huiskamer
                  - media_player.serre
