---
- id: 852e44fe-4a98-4d0f-991b-ca719d0826f5
  alias: Remote - Cover Up
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "08:6b:d7:ff:fe:5d:b1:49"
      command: "up_open"
  action:
    - service: cover.open_cover
      entity_id: cover.main_bedroom
- id: cf4c82c2-9503-4c3c-a119-dd30c5280c63
  alias: Remote - Cover Down
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: "08:6b:d7:ff:fe:5d:b1:49"
      command: "down_close"
  action:
    - service: cover.close_cover
      entity_id: cover.main_bedroom
