---
- id: upstairs_santi_bedroom
  alias: Upstairs - Santi Bedroom
  trigger:
    platform: mqtt
    topic: stat/Light_Switch_Santi/BUTTON1T
    payload: '{"TRIG":"DOUBLE"}'
  action:
    - service: light.toggle
      entity_id: light.wled_santi
