---
- id: 4604b2f6-b57f-4e27-88c7-2ad65f214f1b
  alias: Multiroom - Wled Nightlights
  mode: single
  trigger:
    - platform: state
      entity_id:
        - light.wled_elyza
        - light.wled_santi
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.wled_santi
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.wled_santi_nightlight
        - conditions:
            - condition: state
              entity_id: light.wled_elyza
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.wled_elyza_nightligh
