---
- id: 38cfae27-853e-4ded-ab80-c22738c0a57c
  alias: Multiroom - Lights Off When Away
  trigger:
    - platform: state
      entity_id:
        - person.remco
        - person.annemarie
      to: not_home
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'off'
  action:
    choose:
      - conditions:
          - condition: state
            entity_id: group.all_lights
            state: 'on'
          - condition: state
            entity_id: person.remco
            state: not_home
          - condition: state
            entity_id: person.annemarie
            state: not_home
          - condition: state
            entity_id: input_boolean.guest_mode
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            entity_id: group.all_lights
          - service: notify.mobile_app_in2023
            data:
              title: Lights Turned Off!!
              message: Home Assistant Turned The Lights Off!!
