---
- id: ad0d78ac-9c9e-481d-b72b-735f4f9093ef
  alias: WLED Effect
  mode: single
  trigger:
    - platform: state
      entity_id: input_select.wled_effect
    - platform: state
      entity_id: input_number.wled_intensity
    - platform: state
      entity_id: input_select.wled_palette
    - platform: state
      entity_id: input_number.wled_speed
    - platform: state
      entity_id: input_boolean.wled_reverse
  action:
    - service: script.turn_on
      data:
        entity_id: script.wled_effect
