---
- platform: template
  sensors:
    doors:
      friendly_name: "Doors"
      device_class: door
      value_template: >-
        {{ is_state('binary_sensor.backdoor', 'on')
        or is_state('binary_sensor.frontdoor', 'on') }}
