---
- platform: template
  sensors:
    guest_mode:
      friendly_name: "Guest Mode"
      value_template: >-
        {{ is_state('device_tracker.iphonevwendolyn', 'home')
        or is_state('device_tracker.samsung_carla', 'home')
        or is_state('device_tracker.samsung_louis', 'home') }}