---
- platform: template
  sensors:
    next_alarm:
      friendly_name: "Next Alarm"
      value_template: >-
        {{now().strftime("%a %h %d %H:%M %Z %Y") == (((state_attr('sensor.in2023_next_alarm', 'Time in Milliseconds')
        | int / 1000) + 0*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y'))}}
