---
- platform: template
  sensors:
    windows:
      friendly_name: "Windows"
      device_class: window
      value_template: >-
        {{ is_state('binary_sensor.santi_window', 'on')
        or is_state('binary_sensor.main_bedroom_window', 'on')
        or is_state('binary_sensor.bedroom_elyza_window', 'on')
        or is_state('binary_sensor.bathroom_window', 'on') }}
