---
- id: 97d8ed32-3b3b-4f6b-a163-fd1c91c91561
  alias: Attic - Attic Light
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        unique_id: 'd0:cf:5e:ff:fe:ce:9f:b6:1:0x0008'
        command: move
  action:
    - service: light.toggle
      entity_id: light.attic
