---
- id: downstairs_basement_light
  alias: Downstairs - Basement Light
  trigger:
    platform: state
    entity_id:
      - binary_sensor.basement_motion
  mode: restart
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.basement_motion
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.basement_closet
      default:
        - delay: 00:03:00
        - service: light.turn_off
          entity_id: light.basement_closet
