---
- id: downstairs_toilet_light
  alias: Downstairs - Toilet Light
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.toilet_motion
  mode: restart
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.toilet_motion
              state: "on"
          sequence:
            - service: light.turn_on
              entity_id: light.toilet_light
      default:
        - delay: 00:05:00
        - service: light.turn_off
          entity_id: light.toilet_light