---
- platform: command_line
  name: Server Temp
  command: ssh -i /config/.ssh/id_rsa -o 'StrictHostKeyChecking=no' root@10.10.50.200 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: "Â°C"
  value_template: '{{ value | multiply(0.001) }}'
