---
- platform: command_line
  name: 'Server CPU Temp'
  command: "ssh -i /config/.ssh/id_rsa -o StrictHostKeyChecking=no root@10.10.50.200 -t 'cat /sys/class/thermal/thermal_zone0/temp'"
  unit_of_measurement: 'Â°C'
  scan_interval: 300
  value_template: '{{ (value | multiply(0.001)) | round(0) }}'
