---
- id: 72ef6905-f119-44e5-a305-f07eaf05e3e1
  alias: Barn - Barn Light Switch
  trigger:
    - platform: mqtt
      topic: stat/main_switch_backyard/BUTTON1T
      payload: '{"TRIG":"HOLD"}'
  action:
    - service: light.toggle
      entity_id:
        - light.small_barn_light
        - light.barn_light
