---
- id: 3860b0ef-c617-43ff-8ffd-e1c8606a5219
  alias: Notify - New Version Available
  trigger:
    - platform: state
      entity_id: sensor.beta
  action:
    - service: notify.mobile_app_in2023
      data:
        title: New HA Version Available
        message: 'Home Assistant Version {{states(''sensor.beta'')}} Is Now Available'
