---
- id: 8220d3f3-10fa-4b5d-aac1-f5d8bde8d115
  alias: Notify - When Away
  trigger:
    - platform: state
      entity_id:
        - person.annemarie
        - person.remco
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id:
                - person.annemarie
                - person.remco
              state: not_home
            - condition: state
              entity_id:
                - binary_sensor.main_bedroom_window_sensor
                - binary_sensor.santi_bedroom_window_sensor
                - binary_sensor.small_bedroom_window_sensor
                - sensor.bathroom_window_battery
              state: 'on'
          sequence:
            - service: notify.mobile_app_in2023
              data:
                title: Window Open!!!
                message: You Left The House With Window('s) Open!!!
        - conditions:
            - condition: state
              entity_id:
                - person.annemarie
                - person.remco
              state: not_hom
            - condition: state
              entity_id:
                - binary_sensor.frontdoor_door_sensor
                - binary_sensor.kitchen_door_sensor
              state: 'on'
          sequence:
            - service: notify.mobile_app_in2023
              data:
                title: Window Open!!!
                message: You Left The House With Door('s) Open!!!
