---
- id: 7ea402b3-09d7-4413-8995-b80e47298eff
  alias: Notify - Lights On
  trigger:
    platform: state
    entity_id:
      - light.closet_light
      - light.hallway
      - light.basement_closet
      - switch.sonoff_basic
      - light.garden_group
      - light.kitchen
      - light.main_bedroom
      - light.wled_elyza
      - light.wled_santi
      - light.attic
      - light.bedroom_elyza
      - light.bedroom_santi
      - light.patio
  condition:
    - condition: state
      entity_id: 'person.remco'
      state: 'not_home'
    - condition: state
      entity_id: 'person.annemarie'
      state: 'not_home'
    - condition: state
      entity_id: 'binary_sensor.guest_mode'
      state: 'off'
  action:
    service: notify.mobile_app_in2023
    data_template:
      title: "Lights On!!"
      message: >-
        "{{ trigger.to_state.attributes.friendly_name }} is on, but nobody home!!"