---
- id: a87b9291-ea8d-4f5d-8dd9-7219b6867734
  alias: System - Hacs Repo Added
  trigger:
    platform: event
    event_type: hacs/repository
    event_data:
      action: registration
  condition:
    condition: template
    value_template: "{{ trigger.event.data.repository is defined }}"
  action:
    - service: persistent_notification.create
      data_template:
        title: New repository in HACS
        message: >-
          {% set repo = trigger.event.data.repository %}
          {% set id = trigger.event.data.repository_id %}
          [{{ repo }}](/hacs/repository/{{ id }})
          was just added to HACS.
    - service: notify.mobile_app_oneplus88
      data_template:
        title: New repository in HACS
        message: >-
          {% set repo = trigger.event.data.repository %}
          {% set id = trigger.event.data.repository_id %}
          [{{ repo }}](/hacs/repository/{{ id }})
          was just added to HACS.
